RestauranteSoftware/Controllers/ComidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Data.Entitys;
using RestauranteSoftware.Data;

namespace RestauranteSoftware.Controllers
{
    public class ComidasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComidasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comidas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Comidas.ToListAsync());
        }

        // GET: Comidas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comidasEntitys = await _context.Comidas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comidasEntitys == null)
            {
                return NotFound();
            }

            return View(comidasEntitys);
        }

        // GET: Comidas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Comidas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImagenUrl,Nombre,Precio,Descripcion")] ComidasEntitys comidasEntitys)
        {
            if (ModelState.IsValid)
            {

                _context.Add(comidasEntitys);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(comidasEntitys);
        }

        // GET: Comidas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comidasEntitys = await _context.Comidas.FindAsync(id);
            if (comidasEntitys == null)
            {
                return NotFound();
            }
            return View(comidasEntitys);
        }

        // POST: Comidas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImagenUrl,Nombre,Precio,Descripcion")] ComidasEntitys comidasEntitys)
        {
            if (id != comidasEntitys.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comidasEntitys);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComidasEntitysExists(comidasEntitys.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comidasEntitys);
        }

        // GET: Comidas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comidasEntitys = await _context.Comidas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comidasEntitys == null)
            {
                return NotFound();
            }

            return View(comidasEntitys);
        }

        // POST: Comidas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comidasEntitys = await _context.Comidas.FindAsync(id);
            if (comidasEntitys != null)
            {
                _context.Comidas.Remove(comidasEntitys);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComidasEntitysExists(int id)
        {
            return _context.Comidas.Any(e => e.Id == id);
        }
        
    }
}

RestauranteSoftware/Controllers/EstadosPedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Data.Entitys;
using RestauranteSoftware.Data;

namespace RestauranteSoftware.Controllers
{
    public class EstadosPedidosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EstadosPedidosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EstadosPedidos
        public async Task<IActionResult> Index()
        {
            return View(await _context.EstadosPedidos.ToListAsync());
        }

        // GET: EstadosPedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadosPedidosEntitys = await _context.EstadosPedidos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estadosPedidosEntitys == null)
            {
                return NotFound();
            }

            return View(estadosPedidosEntitys);
        }

        // GET: EstadosPedidos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EstadosPedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre")] EstadosPedidosEntitys estadosPedidosEntitys)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estadosPedidosEntitys);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estadosPedidosEntitys);
        }

        // GET: EstadosPedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadosPedidosEntitys = await _context.EstadosPedidos.FindAsync(id);
            if (estadosPedidosEntitys == null)
            {
                return NotFound();
            }
            return View(estadosPedidosEntitys);
        }

        // POST: EstadosPedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre")] EstadosPedidosEntitys estadosPedidosEntitys)
        {
            if (id != estadosPedidosEntitys.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estadosPedidosEntitys);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstadosPedidosEntitysExists(estadosPedidosEntitys.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estadosPedidosEntitys);
        }

        // GET: EstadosPedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadosPedidosEntitys = await _context.EstadosPedidos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estadosPedidosEntitys == null)
            {
                return NotFound();
            }

            return View(estadosPedidosEntitys);
        }

        // POST: EstadosPedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estadosPedidosEntitys = await _context.EstadosPedidos.FindAsync(id);
            if (estadosPedidosEntitys != null)
            {
                _context.EstadosPedidos.Remove(estadosPedidosEntitys);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstadosPedidosEntitysExists(int id)
        {
            return _context.EstadosPedidos.Any(e => e.Id == id);
        }
    }
}

RestauranteSoftware/Views/Shared/VCajero/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Unidad3P1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Unidad3P1.styles.css" asp-append-version="true" />
</head>

<body class="d-flex flex-column min-vh-100 bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">Cafeteria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <!-- Add other navigation items if needed -->
                    </ul>
                    <partial name="_LoginPartial" class="container-fluid text-center" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid flex-grow-1">
        <div class="row h-100">
            @if (User.Identity.IsAuthenticated)
            {
                <nav class="col-md-2 d-none d-md-block sidebar">
                    <div class="position-sticky">
                        <ul class="nav flex-column p-3">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Comidas" asp-action="Index">Comidas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="EstadosPedidos" asp-action="Index">Estados de Pedidos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="DetallesPedidos" asp-action="Index">Detalles de Pedidos</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            }
            else
            {
                <nav class="col-md-2 d-none d-md-block sidebar">
                    <div class="position-sticky">
                        <ul class="nav flex-column p-3">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            }
            <main role="main" class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container m-3">
            <span class="text-muted">&copy; 2024 - UniDAD_3_P1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></span>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>