RestauranteSoftware/Controllers/ComidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Data.Entitys;
using RestauranteSoftware.Data;

namespace RestauranteSoftware.Controllers
{
    public class ComidasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComidasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comidas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Comidas.ToListAsync());
        }

        // GET: Comidas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comidasEntitys = await _context.Comidas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comidasEntitys == null)
            {
                return NotFound();
            }

            return View(comidasEntitys);
        }

        // GET: Comidas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Comidas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImagenUrl,Nombre,Precio,Descripcion")] ComidasEntitys comidasEntitys)
        {
            if (ModelState.IsValid)
            {

                _context.Add(comidasEntitys);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(comidasEntitys);
        }

        // GET: Comidas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comidasEntitys = await _context.Comidas.FindAsync(id);
            if (comidasEntitys == null)
            {
                return NotFound();
            }
            return View(comidasEntitys);
        }

        // POST: Comidas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImagenUrl,Nombre,Precio,Descripcion")] ComidasEntitys comidasEntitys)
        {
            if (id != comidasEntitys.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comidasEntitys);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComidasEntitysExists(comidasEntitys.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comidasEntitys);
        }

        // GET: Comidas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comidasEntitys = await _context.Comidas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comidasEntitys == null)
            {
                return NotFound();
            }

            return View(comidasEntitys);
        }

        // POST: Comidas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comidasEntitys = await _context.Comidas.FindAsync(id);
            if (comidasEntitys != null)
            {
                _context.Comidas.Remove(comidasEntitys);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComidasEntitysExists(int id)
        {
            return _context.Comidas.Any(e => e.Id == id);
        }
        
    }
}

RestauranteSoftware/Controllers/PedidosEntitysController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Data.Entitys;
using RestauranteSoftware.Data;
using RestauranteSoftware.viewModels;
using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Http.Extensions;


namespace RestauranteSoftware.Controllers
{
    public class PedidosEntitysController : Controller
    {
        private readonly ApplicationDbContext _context;
        ListaComida listaComida = ListaComida.getListCom();
        private readonly IConverter _converter;
        public PedidosEntitysController(ApplicationDbContext context, IConverter converter)
        {
            _context = context;
            _converter = converter;

        }


        public async Task<IActionResult> Reporte(string fecha)
        {
            if (!DateTime.TryParse(fecha, out DateTime fechaConvertida))
            {
                // Manejar error si la fecha no es válida
                return BadRequest("Fecha inválida.");
            }

            var applicationDbContext = _context.Pedidos
            .Include(p => p.EstadoPedido)
            .Where(p => p.Fecha.Date == fechaConvertida.Date
                && p.EstadoPedido.Nombre == "Pagado");


            // Crear el modelo de vista
            PedidosViews pedidoViewModel = new PedidosViews
            {
                // Asignar los pedidos filtrados
                pedidos = await applicationDbContext.ToListAsync(),

                // Filtrar detalles de pedidos relacionados
                detallesPedidos = await _context.DetallesPedidos
                    .Include(x => x.Comida)
                    .Where(dp => dp.Pedido.Fecha.Date == fechaConvertida.Date && (dp.Pedido.EstadoPedido.Nombre == "Pagado" || dp.Pedido.EstadoPedido.Nombre == "Completado"))
                    .ToListAsync()
            };

            // Si no hay pedidos, enviar un mensaje indicando que no hay pedidos para esa fecha
            if (!pedidoViewModel.pedidos.Any())
            {
                // No hay pedidos para esa fecha
                ViewData["NoPedidos"] = "No hay pedidos para la fecha seleccionada.";
            }

            return View(pedidoViewModel);
        }


        public async Task<IActionResult> ReportePagados(string fecha)
        {
            if (!DateTime.TryParse(fecha, out DateTime fechaConvertida))
            {
                // Manejar error si la fecha no es válida
                return BadRequest("Fecha inválida.");
            }

            var applicationDbContext = _context.Pedidos
            .Include(p => p.EstadoPedido)
            .Where(p => p.Fecha.Date == fechaConvertida.Date
                && (p.EstadoPedido.Nombre == "Pagado" || p.EstadoPedido.Nombre == "Completado"));


            // Crear el modelo de vista
            PedidosViews pedidoViewModel = new PedidosViews
            {
                // Asignar los pedidos filtrados
                pedidos = await applicationDbContext.ToListAsync(),

                // Filtrar detalles de pedidos relacionados
                detallesPedidos = await _context.DetallesPedidos
                    .Include(x => x.Comida)
                    .Where(dp => dp.Pedido.Fecha.Date == fechaConvertida.Date && (dp.Pedido.EstadoPedido.Nombre == "Pagado" || dp.Pedido.EstadoPedido.Nombre == "Completado"))
                    .ToListAsync()
            };

            // Si no hay pedidos, enviar un mensaje indicando que no hay pedidos para esa fecha
            if (!pedidoViewModel.pedidos.Any())
            {
                // No hay pedidos para esa fecha
                ViewData["NoPedidos"] = "No hay pedidos para la fecha seleccionada.";
            }

            return View(pedidoViewModel);
        }




        public async Task<IActionResult> CrearReporte(string fecha)
        {

            if (!DateTime.TryParse(fecha, out DateTime fechaConvertida))
            {
                // Manejar error si la fecha no es válida
                return BadRequest("Fecha inválida.");
            }

            // Construir la URL completa de la vista que se desea convertir a PDF
            string baseUrl = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
            string urlPagina = $"{baseUrl}/PedidosEntitys/Reporte?fecha={fecha}";

            // Configuración del documento PDF
            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = new GlobalSettings
                {
                    PaperSize = PaperKind.A4,
                    Orientation = Orientation.Portrait,
                    Margins = new MarginSettings { Top = 10, Bottom = 10, Left = 10, Right = 10 },
                }
            };

            // Agrega los objetos (páginas) al documento PDF
            pdf.Objects.Add(new ObjectSettings
            {
                Page = urlPagina,
                WebSettings = new WebSettings
                {
                    DefaultEncoding = "utf-8",
                    Background = false // Esto deshabilita imágenes de fondo
                }
            });

            // Convierte el documento a PDF
            var archivoPDF = _converter.Convert(pdf);

            // Genera un nombre único para el archivo PDF
            string nombrePDF = $"reporte_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";

            // Devuelve el archivo PDF como una descarga
            return File(archivoPDF, "application/pdf", nombrePDF);
        }



        public async Task<IActionResult> CrearReportePagados(string fecha)
        {

            if (!DateTime.TryParse(fecha, out DateTime fechaConvertida))
            {
                // Manejar error si la fecha no es válida
                return BadRequest("Fecha inválida.");
            }

            // Construir la URL completa de la vista que se desea convertir a PDF
            string baseUrl = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
            string urlPagina = $"{baseUrl}/PedidosEntitys/ReportePagados?fecha={fecha}";

            // Configuración del documento PDF
            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = new GlobalSettings
                {
                    PaperSize = PaperKind.A4,
                    Orientation = Orientation.Portrait,
                    Margins = new MarginSettings { Top = 10, Bottom = 10, Left = 10, Right = 10 },
                }
            };

            // Agrega los objetos (páginas) al documento PDF
            pdf.Objects.Add(new ObjectSettings
            {
                Page = urlPagina,
                WebSettings = new WebSettings
                {
                    DefaultEncoding = "utf-8",
                    Background = false // Esto deshabilita imágenes de fondo
                }
            });

            // Convierte el documento a PDF
            var archivoPDF = _converter.Convert(pdf);

            // Genera un nombre único para el archivo PDF
            string nombrePDF = $"reporteCocinero_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";

            // Devuelve el archivo PDF como una descarga
            return File(archivoPDF, "application/pdf", nombrePDF);
        }







        // GET: PedidosEntitys
        public async Task<IActionResult> Index()
        {

            ViewData["EstadoId"] = new SelectList(_context.EstadosPedidos, "Id", "Nombre");
            var applicationDbContext = _context.Pedidos
                .Include(p => p.EstadoPedido)
                .OrderByDescending(p => p.IsPrioridad) // Prioritarios primero
                .ThenByDescending(p => p.Fecha); // Más recientes primero

            PedidosViews pedidoViewModel = new PedidosViews();
            pedidoViewModel.pedidos = await applicationDbContext.ToListAsync();
            pedidoViewModel.detallesPedidos = await _context.DetallesPedidos
                .Include(x => x.Comida)
                .ToListAsync();

            return View(pedidoViewModel);
        }





        // GET: PedidosEntitys/Create
        public async Task<IActionResult> Create(PedidosComidas pedidosComidas)
        {

            ViewData["EstadoId"] = new SelectList(_context.EstadosPedidos, "Id", "Nombre");
            if (pedidosComidas.Comidas == null)
            {
                listaComida.reiniciarVar();
                
            }
            pedidosComidas = new PedidosComidas();
            var pedido = new PedidosEntitys
            {
                Fecha = DateTime.Now // Asigna la fecha actual al campo Fecha
            };
            pedidosComidas.Pedido = pedido;
            var comidas = new List<ComidasEntitys>();
            comidas = await _context.Comidas.ToListAsync();
            pedidosComidas.Comidas = comidas;
            pedidosComidas.ListaComida = listaComida;
            return View(pedidosComidas);
        }

        // POST: PedidosEntitys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PedidosEntitys pedidosEntitys, int Totalito, bool IsPrioridad ,int Nro)
        {
            if (ModelState.IsValid)
            {
               
                // Asigna la fecha actual al campo Fecha si es necesario
                pedidosEntitys.EstadoId = 1; //id de pendiente
                pedidosEntitys.Fecha = DateTime.Now;
                pedidosEntitys.TotalPedido = Totalito;
                pedidosEntitys.IsPrioridad = IsPrioridad;
                pedidosEntitys.NroMesa = Nro;
                var list = listaComida.getIdCom();
                var listCant = listaComida.getCant();
                _context.Add(pedidosEntitys);

                await _context.SaveChangesAsync();
                for (int i = 0; i < listaComida.getIdCom().Count; i++)

RestauranteSoftware/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestauranteSoftware</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestauranteSoftware.styles.css" asp-append-version="true" />
</head>

<body class="d-flex flex-column min-vh-75">
    <header class="mt-0 shadow-sm">
        <nav class="navbar navbar-expand-sm navbar-light">
            <div class="container-fluid">
                <!-- Logo y nombre de la marca -->
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index" style="color: #007acc;">
                    <img src="https://i.ibb.co/g4NdFCz/Firefly-un-logo-con-una-hamburguesa-con-un-rayo-fondo-celeste-94803.jpg"
                         alt="Logo"
                         class="rounded-circle me-3"
                         style="width: 4em; height: 4em;">
                    <span class="fs-4 fw-bold">SpeedFoost</span>
                </a>

                <!-- Botón colapsable para dispositivos pequeños -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon "></span>
                </button>

                <!-- Navegación -->
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNav">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Cajero") || User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-primary" asp-area="" asp-controller="Comidas" asp-action="Index">Comidas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-primary" asp-area="" asp-controller="PedidosEntitys" asp-action="Index">Pedidos</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-primary" asp-area="" asp-controller="EstadosPedidosEntitys" asp-action="Index">Estados de Pedidos</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="PedidosEntitys" asp-action="Comanda">Comanda</a>
                            </li>
                        }
                    </ul>
                    <!-- Login parcial -->
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>





    <div class="container-fluid main  flex-grow-1">
        <main role="main" class="px-md-4">
            @RenderBody()
        </main>
    </div>

    <footer class="footer mt-auto py-3">
        <div class="container m-3">
            <span>Restaurante comida rápida para sastifacer tu paladar @* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@</span>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

RestauranteSoftware/Views/Shared/_LayoutReport.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestauranteSoftware</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestauranteSoftware.styles.css" asp-append-version="true" />
</head>

<body class="d-flex flex-column min-vh-75">

    <div class="container-fluid flex-grow-1">
        <main role="main" class="px-md-4">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>